### ISSUE TITLE
Can not change Config or update plugin 

### ISSUE THREAD

**Issue by Bankaifan** [mkellsy/homebridge-config-ui#24]
Hi,

i have the problem that changes made to the config or the update-process don't have any effect. Even so the Update does not work. 
Simply nothing happens even if the website tells me (and the log) that the update is done.

Any ideas?

**Comment by shidevil** [comment]
Hi,

Could you check if you are running with systemd? Is it using a root account?

**Comment by Bankaifan** [comment]
Hi,

Homebridge is Running as systemd and is Running under root.

I tried The homebridge-upgrade today...

The log says „homebridge Server upgraded“ but nothing was done. I can rerun The upgrade several times

**Comment by shidevil** [comment]
Did you set the base path? Which branch are u using? Masters of my pull request

**Comment by shidevil** [comment]
Or*

**Comment by mkellsy** [comment]
This is an issue is caused because Homebridge prefers global, and so do the plugins. I am working on a new project [Homebridge(X)](https://github.com/mkellsy/homebridge-x) that creates a wrapper around Homebridge that manages the state, configs and plugins. This addresses this issue. The project isn't ready yet but the API works.
