### ISSUE TITLE
restart not working (Mac launchd)

### ISSUE THREAD

**Issue by ifunlisted** [mkellsy/homebridge-config-ui#38]
I'm using...
"restart" : "launchctl unload ~/Library/LaunchAgents/com.homebridge.server.plist && launchctl load ~/Library/LaunchAgents/com.homebridge.server.plist"
...for restart in config.json, but it doesn't seem to be working. It does work in Terminal.

When I use the Restart button on the web ui, it appears to unload fine, but then never reloads.

I'm running on a Mac, using launchd

**Comment by mkellsy** [comment]
That's the main reason why I used supervisord. It allows for a restard, where launchd does not. The issue is the interface runs as a plug-in to homebridge, and it shuts down without any way to come back.

I have started planning a stack version where the UI runs as the master and homebridge is a child process. This would also help with dynamic plugins and configuration.

**Comment by mkellsy** [comment]
I am working on a new project called [Homebridge(X)](https://github.com/mkellsy/homebridge-x) that address this issue. It is a wrapper that makes it easier to control and configure Homebridge.
